# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/theraven/Documents/Work/Teaching/Compilers ACS Module/Coursework/Resources/CellularAutomata"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/theraven/Documents/Work/Teaching/Compilers ACS Module/Coursework/Resources/CellularAutomata"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/theraven/Documents/Work/Teaching/Compilers ACS Module/Coursework/Resources/CellularAutomata/CMakeFiles" "/Users/theraven/Documents/Work/Teaching/Compilers ACS Module/Coursework/Resources/CellularAutomata/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/theraven/Documents/Work/Teaching/Compilers ACS Module/Coursework/Resources/CellularAutomata/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cellatom

# Build rule for target.
cellatom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cellatom
.PHONY : cellatom

# fast build rule for target.
cellatom/fast:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/build
.PHONY : cellatom/fast

Pegmatite/ast.o: Pegmatite/ast.cc.o
.PHONY : Pegmatite/ast.o

# target to build an object file
Pegmatite/ast.cc.o:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/Pegmatite/ast.cc.o
.PHONY : Pegmatite/ast.cc.o

Pegmatite/ast.i: Pegmatite/ast.cc.i
.PHONY : Pegmatite/ast.i

# target to preprocess a source file
Pegmatite/ast.cc.i:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/Pegmatite/ast.cc.i
.PHONY : Pegmatite/ast.cc.i

Pegmatite/ast.s: Pegmatite/ast.cc.s
.PHONY : Pegmatite/ast.s

# target to generate assembly for a file
Pegmatite/ast.cc.s:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/Pegmatite/ast.cc.s
.PHONY : Pegmatite/ast.cc.s

Pegmatite/parser.o: Pegmatite/parser.cc.o
.PHONY : Pegmatite/parser.o

# target to build an object file
Pegmatite/parser.cc.o:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/Pegmatite/parser.cc.o
.PHONY : Pegmatite/parser.cc.o

Pegmatite/parser.i: Pegmatite/parser.cc.i
.PHONY : Pegmatite/parser.i

# target to preprocess a source file
Pegmatite/parser.cc.i:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/Pegmatite/parser.cc.i
.PHONY : Pegmatite/parser.cc.i

Pegmatite/parser.s: Pegmatite/parser.cc.s
.PHONY : Pegmatite/parser.s

# target to generate assembly for a file
Pegmatite/parser.cc.s:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/Pegmatite/parser.cc.s
.PHONY : Pegmatite/parser.cc.s

ast.o: ast.cc.o
.PHONY : ast.o

# target to build an object file
ast.cc.o:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/ast.cc.o
.PHONY : ast.cc.o

ast.i: ast.cc.i
.PHONY : ast.i

# target to preprocess a source file
ast.cc.i:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/ast.cc.i
.PHONY : ast.cc.i

ast.s: ast.cc.s
.PHONY : ast.s

# target to generate assembly for a file
ast.cc.s:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/ast.cc.s
.PHONY : ast.cc.s

compiler.o: compiler.cc.o
.PHONY : compiler.o

# target to build an object file
compiler.cc.o:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/compiler.cc.o
.PHONY : compiler.cc.o

compiler.i: compiler.cc.i
.PHONY : compiler.i

# target to preprocess a source file
compiler.cc.i:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/compiler.cc.i
.PHONY : compiler.cc.i

compiler.s: compiler.cc.s
.PHONY : compiler.s

# target to generate assembly for a file
compiler.cc.s:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/compiler.cc.s
.PHONY : compiler.cc.s

interpreter.o: interpreter.cc.o
.PHONY : interpreter.o

# target to build an object file
interpreter.cc.o:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/interpreter.cc.o
.PHONY : interpreter.cc.o

interpreter.i: interpreter.cc.i
.PHONY : interpreter.i

# target to preprocess a source file
interpreter.cc.i:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/interpreter.cc.i
.PHONY : interpreter.cc.i

interpreter.s: interpreter.cc.s
.PHONY : interpreter.s

# target to generate assembly for a file
interpreter.cc.s:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/interpreter.cc.s
.PHONY : interpreter.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/main.cc.s
.PHONY : main.cc.s

parser.o: parser.cc.o
.PHONY : parser.o

# target to build an object file
parser.cc.o:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/parser.cc.o
.PHONY : parser.cc.o

parser.i: parser.cc.i
.PHONY : parser.i

# target to preprocess a source file
parser.cc.i:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/parser.cc.i
.PHONY : parser.cc.i

parser.s: parser.cc.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cc.s:
	$(MAKE) -f CMakeFiles/cellatom.dir/build.make CMakeFiles/cellatom.dir/parser.cc.s
.PHONY : parser.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cellatom"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pegmatite/ast.o"
	@echo "... Pegmatite/ast.i"
	@echo "... Pegmatite/ast.s"
	@echo "... Pegmatite/parser.o"
	@echo "... Pegmatite/parser.i"
	@echo "... Pegmatite/parser.s"
	@echo "... ast.o"
	@echo "... ast.i"
	@echo "... ast.s"
	@echo "... compiler.o"
	@echo "... compiler.i"
	@echo "... compiler.s"
	@echo "... interpreter.o"
	@echo "... interpreter.i"
	@echo "... interpreter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

